name: Build and Push to Local Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR
        run: chmod +x ./gradlew && ./gradlew clean build -x test

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t 127.0.0.1:5000/orderprocessor:$IMAGE_TAG .
          docker push 127.0.0.1:5000/orderprocessor:$IMAGE_TAG
          echo "✅ Pushed: 127.0.0.1:5000/orderprocessor:$IMAGE_TAG"